name: Build
on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  build:
    permissions:
      contents: read
      checks: write
      statuses: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        java: [17, 21]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: Setup Java
        uses: actions/setup-java@3b6c050358614dd082e53cdbc55580431fc4e437
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@245c8a24de79c0dbeabaf19ebcbbd3b2c36f278d
      - name: Build with Gradle
        run: ./gradlew build
